spring:
  application:
    name: fido2-poc

app:
  backend-url: https://api.dmgiangi.dev

entra-id:
    credential:
      client-id: ${ENTRA_CLIENT_ID}
      client-secret: ${ENTRA_CLIENT_SECRET}
      tenant-id: ${ENTRA_TENANT_ID}
